/**
 * @fileoverview gRPC-Web generated client stub for crimemap.service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.1
// source: crime.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.crimemap = {};
proto.crimemap.service = require('./crime_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.crimemap.service.CrimeMapClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.crimemap.service.CrimeMapPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.crimemap.service.GetCrimesRequest,
 *   !proto.crimemap.service.GetCrimesResponse>}
 */
const methodDescriptor_CrimeMap_GetCrimes = new grpc.web.MethodDescriptor(
  '/crimemap.service.CrimeMap/GetCrimes',
  grpc.web.MethodType.UNARY,
  proto.crimemap.service.GetCrimesRequest,
  proto.crimemap.service.GetCrimesResponse,
  /**
   * @param {!proto.crimemap.service.GetCrimesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.crimemap.service.GetCrimesResponse.deserializeBinary
);


/**
 * @param {!proto.crimemap.service.GetCrimesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.crimemap.service.GetCrimesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.crimemap.service.GetCrimesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.crimemap.service.CrimeMapClient.prototype.getCrimes =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/crimemap.service.CrimeMap/GetCrimes',
      request,
      metadata || {},
      methodDescriptor_CrimeMap_GetCrimes,
      callback);
};


/**
 * @param {!proto.crimemap.service.GetCrimesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.crimemap.service.GetCrimesResponse>}
 *     Promise that resolves to the response
 */
proto.crimemap.service.CrimeMapPromiseClient.prototype.getCrimes =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/crimemap.service.CrimeMap/GetCrimes',
      request,
      metadata || {},
      methodDescriptor_CrimeMap_GetCrimes);
};


module.exports = proto.crimemap.service;

